name: Github Package Publisher

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Decode Signature
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SEC_RING_DECRYPT_PASSWORD }}" --output secring.gpg secring.crypt.gpg

    - name: Lint & JVM Checks
      run: ./gradlew check
      if: "!contains(github.event.head_commit.message, '[lint skip]')"

    - name: Publish Maven Repository
      run: ./gradlew publishMavenPublicationToMavenRepository -Psigning.secretKeyRingFile=./secring.gpg -Psigning.password="${{ secrets.SEC_RING_PASSWORD }}" -Psigning.keyId="${{ secrets.SEC_RING_KEY_ID }}"
      if: "!contains(github.event.head_commit.message, '[publish skip]')"
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}